# version: '3.8'

services:
  # Laravel Service
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app_network
    depends_on:
      - db

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nas_db
      MYSQL_USER: nasfarm
      MYSQL_PASSWORD: nasfarm12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # Node.js Service for Vue.js
  node:
    image: node:18
    container_name: vuejs_app
    working_dir: /usr/src/app
    volumes:
      - ./vuejs:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - app_network

  # Nginx Service
  web:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
